### PR TITLE
Upgrade Admob SDK and Google ads SDK to latest's

### PR DESCRIPTION
**Pull request by EYALIN**

### CODE REVIEW

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
According to my knowledge this plug-in is using `Google-Mobile-Ads-SDK` version **8.13.0**

Google states that all version between **7** and **19** will [completely stop functioning](https://developers.google.com/admob/android/deprecation) from April 1st 2023.

Are my findings correct and what can we do - as a community - to update this plug-in and keep receiving ads?

Clipboard 1

**Comment by VVelda** [comment]
> According to my knowledge this plug-in is using `Google-Mobile-Ads-SDK` version **8.13.0**

Not really, you are confusing iOS versioning ([the newest is 10.3.0](https://developers.google.com/admob/ios/rel-notes)) and Android version sunset plans.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> > According to my knowledge this plug-in is using `Google-Mobile-Ads-SDK` version **8.13.0**
> 
> Not really, you are confusing iOS versioning ([the newest is 10.3.0](https://developers.google.com/admob/ios/rel-notes)) and Android version sunset plans.

**I think you are right and I am wrong.**

Nevertheless "a version" should be upgraded, whether it is `iOS` or `Android`?

The Android version will be active for a couple of months now (with some luck a year or two), but the IOS version needs updates soon.

**And in the "far" future we need to make a plan for maintaining this plug-in by ourself?**

**Comment by ratson** [comment]
Close as the latest alpha version supports the latest SDK.

**Pull request closed without merging**
